[project]
name = "berrywave-edi"
version = "0.1.0"
description = "Python interface to the BerryWave EDI engine"
requires-python = ">=3.14"
dependencies = [
    "jpype1"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["berrywave"]

[tool.setuptools.package-data]
berrywave = ["java/*.jar"]

[project.optional-dependencies]
dev = [
    "pytest"
]